### ISSUE TITLE
Missing file and code?

### ISSUE THREAD

**Issue by ujeong1** [RingBDStack/FinEvent#1]
Hi, 

First of all, thanks for the nice work and I am excited to know this practical work on event detection.

I've encountered a problem while running your codes, the most obvious problem is that there is no "utils/custom_message_graph.py" in the utils directory. Also, I think steps 1~3 are generally not runnable with a given dataset in the GoogleDrive.

Am I missing something for running this code? Following is the error I encounter when I try the 1st step of "save_edge_index.py"

//ERROR CODE
Traceback (most recent call last):
  File "utils/save_edge_index.py", line 9, in <module>
    save_multi_relational_graph(data_path, relation_ids, [0, i])
  File "/home/local/ASUAD/ujeong1/PycharmProjects/FinEvent/utils/gen_dataset.py", line 123, in save_multi_relational_graph
    relation_edge_index = sparse_trans(os.path.join(loadpath, str(mode[1]), 's_m_tid_%s_tid.npz' % relation))
  File "/home/local/ASUAD/ujeong1/PycharmProjects/FinEvent/utils/gen_dataset.py", line 14, in sparse_trans
    relation = sparse.load_npz(datapath)
  File "/home/local/ASUAD/ujeong1/anaconda3/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 123, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/local/ASUAD/ujeong1/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'incremental_cross_English_68841/0/s_m_tid_entity_tid.npz

**Comment by ujeong1** [comment]
Changed the title

**Comment by antoniojesuus** [comment]
Hi, did you figured it out how to run the code?, I need help too.
